<?php

//function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
//  dpm($form_id);
//  ksm($form);
//}

function mymodule_entity_presave(Drupal\Core\Entity\EntityInterface $entity){

  switch ($entity->bundle()) {
    // Here you modify only your day content type
    case 'article':
      // Setting the title with the value of field_date.
      $entity->setTitle('New title');
      ksm($entity->getTitle());
      break;
  }
}
